### ISSUE TITLE
Blizzget crashing

### ISSUE THREAD

**Issue by Haskaalo** [d07RiV/blizzget#1]
Everytime I click the program code.

**Comment by d07RiV** [comment]
Which program are you selecting? It works for d3t, but it does indeed crash for pro (Overwatch), I'll look into it.

**Comment by Haskaalo** [comment]
I'm selecting the Overwatch dev Indeed

**Comment by Toyz** [comment]
Dev is encrypted data

**Comment by d07RiV** [comment]
An update, CDN config no longer has a list of all available builds, which the program was looking for. It also means that you will not be able to locate any builds except the current one, so I'm not sure if there's any use in this anymore.

**Comment by Tintir** [comment]
update pls!
